#!/usr/bin/env python3
"""Generate the Beamer source and rehearsal documents from one content file."""
from __future__ import annotations
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]

def tex(text):
    table={'\\':r'\textbackslash{}','&':r'\&','%':r'\%','$':r'\$','#':r'\#','_':r'\_','{':r'\{','}':r'\}','~':r'\textasciitilde{}','^':r'\textasciicircum{}','\n':r'\\'}
    return ''.join(table.get(c,c) for c in text)

def node(x,y,w,text,size=11,color='paper',bold=False):
    return (f'\\node[anchor=north west,inner sep=0pt,text width={w}cm,align=left] at ({x},{y}) '
            + '{'+f'\\color{{{color}}}\\fontsize{{{size}}}{{{size*1.17:.1f}}}\\selectfont '
            +r'\raggedright\hyphenpenalty=10000\exhyphenpenalty=10000 '+(r'\bfseries ' if bold else '')+tex(text)+'};\n')

def rect(x,y,w,h,color='panel'):
    return f'\\fill[{color}] ({x},{y}) rectangle ({x+w},{y+h});\n'

def main():
    data=json.loads((ROOT/'slides/content.json').read_text())
    out=[r'''% Generated by tools/build_deck.py from slides/content.json.
\documentclass[aspectratio=169,11pt]{beamer}
\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usepackage{tikz}
\usepackage{listings}
\definecolor{void}{HTML}{101214}
\definecolor{panel}{HTML}{1A1F23}
\definecolor{paper}{HTML}{F0F0E8}
\definecolor{acid}{HTML}{C7FF48}
\definecolor{alarm}{HTML}{FF756B}
\definecolor{muted}{HTML}{A7ADB3}
\setbeamercolor{background canvas}{bg=void}
\setbeamercolor{normal text}{fg=paper}
\setbeamertemplate{navigation symbols}{}
\setbeamertemplate{footline}{}
\lstset{basicstyle=\ttfamily\fontsize{9}{11}\selectfont\color{paper},
  breaklines=true,columns=fullflexible,keepspaces=true,showstringspaces=false,
  aboveskip=0pt,belowskip=0pt}
\hypersetup{pdftitle={Your Agent Escaped Without Escaping the Sandbox},
 pdfauthor={Yossi Eliaz},pdfsubject={AI Agent Security Summit, New York, October 21, 2026}}
\begin{document}
''']
    snippets=ROOT/'slides/snippets'; snippets.mkdir(exist_ok=True)
    script=['# '+data['title'],'','**Yossi Eliaz | AI Agent Security Summit, New York | 21 October 2026**','',
            '11 main slides. Target delivery: 14 minutes, including pauses; hard slot: 15 minutes. These timings are rehearsal targets, not a measured live performance.','']
    notes=['# Speaker notes and source ledger','','Generated from `slides/content.json`. Main delivery uses slides 1-11. Appendix slides are for Q&A.','']
    for i,s in enumerate(data['slides'],1):
        a=[r'\begin{frame}[plain]',r'\begin{tikzpicture}[remember picture,overlay]',r'\begin{scope}[shift={(current page.north west)},x=1cm,y=-1cm]']
        a.append(node(1,.48,14,s['eyebrow'],8.5,'acid',True))
        kind=s['kind']
        if kind=='title':
            a.append(node(1,1.85,14,s['title'],30,'paper',True))
            a.append(node(1,6.0,14,s['subtitle'],16,'paper',True))
            a.append(node(1,6.8,14,s['affiliation'],10,'muted'))
            a.append(node(1,7.55,14,s['date'],11,'acid'))
        else:
            a.append(node(1,1.12,14,s['title'],22,'paper',True))
            if kind=='reveal':
                for x,label,value,col in [(1,s['left_label'],s['left_value'],'acid'),(8.2,s['right_label'],s['right_value'],'alarm')]:
                    a.append(rect(x,3.4,6.8,2.75))
                    a.append(node(x+.35,3.73,6.1,label,9,'muted',True))
                    a.append(node(x+.35,4.25,6.1,value,38,col,True))
            elif kind in ('case','checker'):
                (snippets/f'{i:02}.txt').write_text(s['code']+'\n')
                a.append(rect(1,3.0,9.3,3.85))
                a.append(f'\\node[anchor=north west,inner sep=0pt] at (1.28,3.27) {{\\begin{{minipage}}[t]{{8.75cm}}\\lstinputlisting{{slides/snippets/{i:02}.txt}}\\end{{minipage}}}};')
                for y,key,col in [(3.14,'outcome','alarm'),(5.23,'control','acid')]:
                    label,value=s[key].split('\n',1)
                    if len(value)>19: value=value.replace(' -> ',' ->\n')
                    a.append(node(10.8,y,4.15,label,9.3,'muted',True))
                    a.append(node(10.8,y+.57,4.15,value,15 if len(value)<19 else 12,col,True))
            elif kind in ('boundary','close','history'):
                rows=s['rows']; start=3.25 if kind=='history' else 3.04
                rh=1.08 if kind=='history' else .87
                for j,(label,text) in enumerate(rows):
                    y=start+j*rh
                    a.append(rect(1,y,0.05,rh-.15,'acid'))
                    a.append(node(1.3,y+.02,3.6,label,10,'acid',True))
                    a.append(node(5.0,y+.02,9.9,text,11.2))
                if 'trust' in s: a.append(node(1,6.95,14,s['trust'],9.3,'muted'))
                if kind=='close': a.append(node(1,7.95,14,s['url'],10,'acid',True))
            elif kind=='pipeline':
                for j,(num,label,description) in enumerate(s['steps']):
                    x=1+j*3.57
                    a.append(rect(x,3.25,3.3,2.12))
                    a.append(node(x+.23,3.5,2.85,num,9,'acid',True))
                    a.append(node(x+.23,3.98,2.85,label,15,'paper',True))
                    a.append(node(x+.23,4.65,2.85,description,8.8,'muted'))
                a.append(node(1,6.0,14,s['equation'],18,'acid',True))
            elif kind=='matrix':
                widths=[3.0,3.6,3.45,3.95]; xs=[1,4,7.6,11.05]
                a.append(rect(1,3.06,14,0.58,'panel'))
                for x,w,h in zip(xs,widths,s['headers']): a.append(node(x+.12,3.19,w-.2,h,8.4,'acid',True))
                rh=.68
                for j,row in enumerate(s['rows']):
                    y=3.75+j*rh
                    if j%2==0:a.append(rect(1,y-.04,14,rh,'panel'))
                    for x,w,value in zip(xs,widths,row):a.append(node(x+.12,y+.1,w-.23,value,9.1))
            elif kind=='code':
                (snippets/f'{i:02}.txt').write_text(s['code']+'\n')
                a.append(rect(1,3,14,3.85))
                a.append(f'\\node[anchor=north west,inner sep=0pt] at (1.3,3.25) {{\\begin{{minipage}}[t]{{13.4cm}}\\lstinputlisting{{slides/snippets/{i:02}.txt}}\\end{{minipage}}}};')
            elif kind=='sources':
                for j,(label,url) in enumerate(s['rows']):
                    y=3.04+j*.9
                    a.append(node(1,y,14,label,10.6,'paper',True))
                    a.append(node(1,y+.39,14,url,7.5,'acid'))
            if 'bottom' in s:
                a.append(node(1,7.23 if kind!='close' else 7.0,14,s['bottom'],11 if kind not in ('matrix','sources') else 10.4,'paper',True))
            if 'foot' in s:
                a.append(node(1,8.13,13.25,s['foot'],6.8,'muted'))
        a.append(node(14.0,8.52,1.0,f'{i:02}/11' if i<=11 else f'APP {chr(65+i-12)}',7,'muted'))
        a.extend([r'\end{scope}',r'\end{tikzpicture}'])
        note=s['time']+'. '+s['cue']+'\n\n'+s['notes']+'\n\n[Sources]\n'+'\n'.join(s['sources'])+'\n[/Sources]'
        a.append(r'\note{'+tex(note)+ '}')
        a.append(r'\end{frame}')
        out.append('\n'.join(a)+'\n')
        title=s['title'].replace('\n',' ')
        notes.extend([f'## {i}. {title}',f'**{s["time"]}**',f'Cue: {s["cue"]}','',s['notes'],'','[Sources]',*s['sources'],'[/Sources]',''])
        if i<=11: script.extend([f'## {i}. {title}',f'**{s["time"]}**  |  *{s["cue"]}*','',s['notes'],''])
    out.append(r'\end{document}'+'\n')
    (ROOT/'slides/talk.tex').write_text('\n'.join(out))
    (ROOT/'TALK.md').write_text('\n'.join(script))
    (ROOT/'SPEAKER_NOTES.md').write_text('\n'.join(notes))
    print(f'Generated {len(data["slides"])} Beamer frames, script and notes')
if __name__=='__main__':main()
